config/routes.rb
# frozen_string_literal: true

require "resque/server"

Rails.application.routes.draw do
  case Rails.env
  when "development"
    default_url_options host: "localhost:3000"
  else
    default_url_options \
      host: "gitjutsu.com",
      protocol: "https"
  end

  mount Resque::Server.new, at: "/resque"

  root to: "application#home"

  get "/auth/github/callback", to: "sessions#create"
  get :sign_out, to: "sessions#destroy"

  resources :repositories, only: %i[index update]

  post "/analyses/:github_id" => "analyses#create", as: "analyse"
end

app/models/github/repository.rb
# frozen_string_literal: true

require "closed_struct"

module Github
  class Repository
    LABEL = "todos"

    def initialize(name:, api:)
      @name = name
      @api = api
      @file_cache = {}
    end

    def create_hook(github_id:)
      hooks.create \
        @name, analyse_url(github_id)
    end

    def toggle_hook(github_id:, hook_id:, active:)
      hooks.update \
        @name, hook_id,
        analyse_url(github_id), active
    end

    def remove_hook(hook_id:)
      hooks.remove @name, hook_id
    end

    def issues
      api.list_issues @name
    end

    def create_issue(title, body)
      api.create_issue @name, title, body, labels: LABEL
    end

    def close_issue(number)
      api.close_issue @name, number
    end

    def pull_request(number:, sha:)
      PullRequest.new \
        api: @api,
        repo_name: @name,
        number: number,
        sha: sha
    end

    def compare_files(before, after)
      compare(before, after)
        .files.map(&Github::File.method(:new))
    end

    private

    def hooks
      @_hooks ||= Hooks.new(api: @api)
    end

    def compare(start, endd)
      api.compare @name, start, endd
    end

    def analyse_url(param)
      Rails.application.routes.url_helpers.analyse_url(param)
    end
  end
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  belongs_to :account
  has_many :analyses

  validates :name, :github_id, :account, presence: true

  after_create_commit :create_github_hook
  after_update_commit :toggle_github_hook
  after_destroy_commit :remove_github_hook

  def full_name
    "#{account.user.github_username}/#{name}"
  end

  delegate :pull_request, :compare_files, to: :source
  delegate :issues, :create_issue, to: :source

  private

  def create_github_hook
    return if hook_id

    source
      .create_hook(github_id: github_id)
      .tap { |hook| update! hook_id: hook.id }
  end

  def toggle_github_hook
    source.toggle_hook \
      github_id: github_id,
      hook_id: hook_id,
      active: active
  end

  def remove_github_hook
    return unless hook_id

    update!(hook_id: nil) if source.remove_hook(hook_id: hook_id)
  end

  def source
    Github::Repository.new \
      name: name,
      api: account.user.github_api
  end
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

class RepositoriesController < ApplicationController
  rescue_from Octokit::NotFound do |exc|
    redirect_to root_path, error: exc.message
  end

  def index
    user_repos   = current_user.repositories
    github_repos = current_user.github_api.repos
      .sort_by { |repo| repo.permissions.admin.to_s }.reverse

    @repos = parse_all(github_repos, user_repos)
  end

  def update
    repository = current_user.account.repositories
      .find_or_initialize_by(github_id: params[:id])

    if repository.update(update_params)
      flash[:success] = t(".#{repository.active ? 'activated' : 'deactivated'}")
    else
      flash[:error] = t(".failed")
    end

    redirect_to repositories_path
  end

  private

  def update_params
    @_update_params ||= params
      .require(:repository)
      .permit(:name, :active)
  end

  def parse_all(github_repos, user_repos)
    github_repos.map do |github_repo|
      user_repo = user_repos
        .find { |ur| ur.github_id == github_repo.id }

      RepositoryForm.new(github_repo, user_repo)
    end
  end
end

app/helpers/repositories_helper.rb
# frozen_string_literal: true

module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(repository) do |f| %>
  <% if repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.slim
section.content
  h1 Repositories

  .col-md-12
    .panel.panel-default
      .panel-body
        .row
          .col-md-4.col-md-offset-8
            .btn-group.pull-right
              button.btn.btn-success.btn-filter data-target="pagado" type="button" Public
              button.btn.btn-warning.btn-filter data-target="pendiente" type="button" Private
              button.btn.btn-danger.btn-filter data-target="cancelado" type="button" Others
              button.btn.btn-default.btn-filter data-target="all" type="button" All

        ol.list-group.row
          - @repos.each do |repo|
            li.repo.list-group-item.col-md-12 data-admin="#{repo.permissions.admin?}" data-private="#{repo.private?}"
              .about.col-md-9
                .media-body
                  h4.title
                    a href="#{repo.html_url}" target="_blank" = repo.full_name
                    / span.repo-type.pull-right.pagado (Admin)
                  p.summary = repo.description

              .status.col-md-2
                - if repo.private?
                  i.fa.fa-lock.col-md-2 title="Private repo"
                - else
                  i.fa.fa-unlock.col-md-2 title="Public repo"

                - if repo.permissions.admin?
                  i.fa.fa-map-signs.col-md-2 title="Admin on this repo"

              = form_with model: repo, url: repository_path(repo.to_param), scope: "repository", class: "col-md-1", data: { behavior: "submit" } do |f|
                = f.hidden_field :name, value: repo.full_name
                label
                  = f.check_box :active

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>