config/routes.rb
# frozen_string_literal: true

require "resque/server"

Rails.application.routes.draw do
  case Rails.env
  when "development"
    default_url_options host: "localhost:3000"
  else
    default_url_options \
      host: "gitjutsu.com",
      protocol: "https"
  end

  mount Resque::Server.new, at: "/resque"

  root to: "application#home"

  get "/auth/github/callback", to: "sessions#create"
  get :sign_out, to: "sessions#destroy"

  resources :repositories, only: %i[index update]

  post "/analyses/:github_id" => "analyses#create", as: "analyse"
end

app/views/layouts/application.slim
doctype html
html
  head
    title Gitjutsu

    = csrf_meta_tags

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"

  body
    nav.navbar.navbar-inverse role="navigation"
      .container
        .navbar-header
          button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          = link_to "Gitjutsu", root_path, class: "navbar-brand"

        - if signed_in?
          .dropdown
            button#dropdownMenu1.btn.btn-default.dropdown-toggle aria-expanded="true" aria-haspopup="true" data-toggle="dropdown" type="button"
              i.fa.fa-user
              span.caret
            ul.dropdown-menu aria-labelledby="dropdownMenu1"
              li
                a href="#" Preferences
              li
                a href="#" Another action
              li.divider role="separator"
              li
                = link_to "Sign out", sign_out_path

    .container
      = flash_messages
      .row
        = yield

    .container
      .center-block
        p
          | Gitjutsu © - #{Time.zone.now.year}
          br
          | Powered By
          a href="http://codelogic.me" target="_blank" &nbsp;YAGNI Group